package com.ppa.exception.test;

import com.ppa.exception.callstack.TestA;

public class TestCase {
	
	private TestA testA;
	
	

}
